// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cricketbook.proto

package cricketbookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Country string `protobuf:"bytes,2,opt,name=Country,proto3" json:"Country,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cricketbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_cricketbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_cricketbook_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CricketBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tournament string    `protobuf:"bytes,1,opt,name=Tournament,proto3" json:"Tournament,omitempty"`
	Player     []*Player `protobuf:"bytes,2,rep,name=Player,proto3" json:"Player,omitempty"`
	FileCsv    []byte    `protobuf:"bytes,3,opt,name=fileCsv,proto3" json:"fileCsv,omitempty"`
}

func (x *CricketBook) Reset() {
	*x = CricketBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cricketbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CricketBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CricketBook) ProtoMessage() {}

func (x *CricketBook) ProtoReflect() protoreflect.Message {
	mi := &file_cricketbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CricketBook.ProtoReflect.Descriptor instead.
func (*CricketBook) Descriptor() ([]byte, []int) {
	return file_cricketbook_proto_rawDescGZIP(), []int{1}
}

func (x *CricketBook) GetTournament() string {
	if x != nil {
		return x.Tournament
	}
	return ""
}

func (x *CricketBook) GetPlayer() []*Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *CricketBook) GetFileCsv() []byte {
	if x != nil {
		return x.FileCsv
	}
	return nil
}

var File_cricketbook_proto protoreflect.FileDescriptor

var file_cricketbook_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x72, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x36, 0x0a,
	0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x71, 0x0a, 0x0b, 0x43, 0x72, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x73, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x73, 0x76, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x73,
	0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x72, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x6f, 0x6f, 0x6b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cricketbook_proto_rawDescOnce sync.Once
	file_cricketbook_proto_rawDescData = file_cricketbook_proto_rawDesc
)

func file_cricketbook_proto_rawDescGZIP() []byte {
	file_cricketbook_proto_rawDescOnce.Do(func() {
		file_cricketbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_cricketbook_proto_rawDescData)
	})
	return file_cricketbook_proto_rawDescData
}

var file_cricketbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cricketbook_proto_goTypes = []interface{}{
	(*Player)(nil),      // 0: tutorial.Player
	(*CricketBook)(nil), // 1: tutorial.CricketBook
}
var file_cricketbook_proto_depIdxs = []int32{
	0, // 0: tutorial.CricketBook.Player:type_name -> tutorial.Player
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cricketbook_proto_init() }
func file_cricketbook_proto_init() {
	if File_cricketbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cricketbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cricketbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CricketBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cricketbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cricketbook_proto_goTypes,
		DependencyIndexes: file_cricketbook_proto_depIdxs,
		MessageInfos:      file_cricketbook_proto_msgTypes,
	}.Build()
	File_cricketbook_proto = out.File
	file_cricketbook_proto_rawDesc = nil
	file_cricketbook_proto_goTypes = nil
	file_cricketbook_proto_depIdxs = nil
}
